### ISSUE TITLE
请问怎么修改聚合的图形大小？

### ISSUE THREAD

**Issue by MaJiaXuan** [maptalks/maptalks.markercluster#22]
想修改聚合图形的大小，要怎么修改？
![image](https://user-images.githubusercontent.com/24503453/65219021-4c5ee280-daea-11e9-8819-c2aca3e03380.png)

**Comment by fuzhenn** [comment]
在options中设置合适的symbol即可
symbol中支持marker相关的属性
如果是文字样式，可以设置textSymbol

**Comment by MaJiaXuan** [comment]
@fuzhenn 请问有没有相关示例？

**Comment by fuzhenn** [comment]
默认的示例里就有
https://maptalks.org/maptalks.markercluster/demo/

**Comment by MaJiaXuan** [comment]
@fuzhenn textSymbol怎么修改字体颜色？textColor? color? haloColor?这三种试了都无效
