### ISSUE TITLE
最新版maptalks地图会使聚合失效

### ISSUE THREAD

**Issue by Particaly** [maptalks/maptalks.markercluster#60]
"maptalks": "^1.0.0-rc.29",
"maptalks.markercluster": "^0.8.5",
该版本maptalks会使地图上应当聚合的marker以及聚合后的marker同时出现在地图上

**Comment by fuzhenn** [comment]
收到

**Comment by fuzhenn** [comment]
cc @deyihu

**Comment by fuzhenn** [comment]
fixed in 0.8.6
https://github.com/maptalks/maptalks.markercluster/commit/a771c83774ef3d1087140b25f9801708029f507d
